/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author HENDRA
 */
public class UtamaForm extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public UtamaForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPendaftaran = new javax.swing.JLabel();
        lblDataStaff = new javax.swing.JLabel();
        lblPembayaranSPP = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        dpUtama = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Utama");
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, -1));

        jLabel10.setFont(new java.awt.Font("Rio Glamour personal use", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SMA N  SAYANG BUNDA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo Bunda.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Rio Glamour personal use", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jl. Kebaikan, Ngemplak, Sleman, Yogyakarta");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        lblPendaftaran.setFont(new java.awt.Font("Rio Glamour personal use", 0, 14)); // NOI18N
        lblPendaftaran.setForeground(new java.awt.Color(255, 255, 255));
        lblPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/registration.png"))); // NOI18N
        lblPendaftaran.setText("   Pendaftaran");
        lblPendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPendaftaranMouseClicked(evt);
            }
        });
        jPanel1.add(lblPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        lblDataStaff.setFont(new java.awt.Font("Rio Glamour personal use", 0, 14)); // NOI18N
        lblDataStaff.setForeground(new java.awt.Color(255, 255, 255));
        lblDataStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/school.png"))); // NOI18N
        lblDataStaff.setText("   Data Staff");
        lblDataStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataStaffMouseClicked(evt);
            }
        });
        jPanel1.add(lblDataStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        lblPembayaranSPP.setFont(new java.awt.Font("Rio Glamour personal use", 0, 14)); // NOI18N
        lblPembayaranSPP.setForeground(new java.awt.Color(255, 255, 255));
        lblPembayaranSPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/SPP.png"))); // NOI18N
        lblPembayaranSPP.setText("   Pembayaran SPP");
        lblPembayaranSPP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPembayaranSPPMouseClicked(evt);
            }
        });
        jPanel1.add(lblPembayaranSPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        dpUtama.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dpUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(dpUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPendaftaranMouseClicked
        // TODO add your handling code here:
        dpUtama.removeAll();
        PendaftaranForm form = new PendaftaranForm();
        form.setVisible(true);
        dpUtama.add(form);
    }//GEN-LAST:event_lblPendaftaranMouseClicked

    private void lblDataStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataStaffMouseClicked
        // TODO add your handling code here:
        dpUtama.removeAll();
        StaffForm form = new StaffForm();
        form.setVisible(true);
        dpUtama.add(form);
    }//GEN-LAST:event_lblDataStaffMouseClicked

    private void lblPembayaranSPPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPembayaranSPPMouseClicked
        // TODO add your handling code here:
        dpUtama.removeAll();
        PembayaranSPP form = new PembayaranSPP();
        form.setVisible(true);
        dpUtama.add(form);
    }//GEN-LAST:event_lblPembayaranSPPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtamaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtamaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpUtama;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDataStaff;
    private javax.swing.JLabel lblPembayaranSPP;
    private javax.swing.JLabel lblPendaftaran;
    // End of variables declaration//GEN-END:variables
}
